name: Generate image
on:
  push:
    tags:
      - v[1-2].[0-9]+.[0-9]+

jobs:
  buildvmimg:
    runs-on: ubuntu-latest
    steps:
      - name: Install qemu tools
        run: |
          sudo apt-get update
          sudo apt-get install make
          sudo apt-get install qemu-system-x86
          sudo apt-get install qemu-utils
      - uses: actions/checkout@v2
      - name: Make vm image
        run: QEMU_NOGRAPHICS=yes make
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: testvmimgs
          path: |
            dist/*qcow2
            dist/*sha256
      - name: Release
        uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "dist/*qcow2,dist/*sha256"
          token: ${{ secrets.GITHUB_TOKEN }}
